apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mon-repo/k8s-manifests.git  # Remplacez par votre repo
    targetRevision: main  # Branche Git
    path: app  # Dossier contenant les fichiers YAML
  destination:
    server: https://kubernetes.default.svc
    namespace: my-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
